### ISSUE TITLE
panic handling hex encoded strings in query

### ISSUE THREAD

**Issue by bwarminski** [rqlite/rqlite#1532]
Filing this just because it's a panic. I'll take a look and see if I can fix it. My early read of the code is that it is incorrectly interpreting this as text.

**What version are you running?**

Version 8, commit unknown, branch unknown, built on unknown (latest from homebrew)

**Are you using Docker or Kubernetes to run your system?**

No

**Are you running a single node or a cluster?**

Single node

**What did you do?**

I'm working on a client library and was playing around with different ways to express binary values. Just to see what it would do, I tested this query from the CLI and REST interface: 

```
CREATE TABLE test_types (id INTEGER PRIMARY KEY, int_column INTEGER, real_column REAL, text_column TEXT, blob_column BLOB, date_column TEXT, boolean_column INTEGER);
INSERT INTO test_types (int_column, real_column, text_column, blob_column, date_column, boolean_column) VALUES (42, 3.14159, 'Hello, World!', x'53514C697465', '2021-09-01', 1), (-42, -3.14159, 'Another Text', x'424C4F42', '2021-12-31', 0), (NULL, NULL, NULL, NULL, NULL, NULL);
select x'53514C697465' from test_types;
```

**What did you expect to happen?**

Query should return binary representation of `SQLLite` three times. 

**What happened instead?**

No results returned, panic on client and server. Here is the server stack:

```
[rqlited] 2023/12/27 15:29:37 http: panic serving 127.0.0.1:51124: runtime error: invalid memory address or nil pointer dereference
goroutine 834 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1868 +0xb9
panic({0x100e0cb60?, 0x101c26e00?})
	runtime/panic.go:920 +0x270
github.com/rqlite/rqlite/db.normalizeRowValues({0xc0004a1460, 0x1, 0x1?}, {0xc0004a13a0, 0x1, 0x0?})
	github.com/rqlite/rqlite/db/db.go:1470 +0x27d
github.com/rqlite/rqlite/db.(*DB).queryStmtWithConn(0xc00001d748?, 0xc0004f2fa0, 0x0, {0x1013c98e0, 0xc000494840})
	github.com/rqlite/rqlite/db/db.go:920 +0x49a
github.com/rqlite/rqlite/db.(*DB).queryWithConn(0xc000116dd0?, 0x1013d6f18?, 0x40?, 0xc000494840)
	github.com/rqlite/rqlite/db/db.go:861 +0x27d
github.com/rqlite/rqlite/db.(*DB).Query(0xc000052a80, 0xc0004f3040, 0x8c?)
	github.com/rqlite/rqlite/db/db.go:809 +0x105
github.com/rqlite/rqlite/store.(*Store).Query(0xc000004300, 0xc000494780)
	github.com/rqlite/rqlite/store/store.go:1093 +0x665
github.com/rqlite/rqlite/http.(*Service).handleQuery(0xc000738240, {0x1013d37d0, 0xc0000c21c0}, 0xc00047e400, 0xc00001db68?)
	github.com/rqlite/rqlite/http/service.go:1216 +0x451
github.com/rqlite/rqlite/http.(*Service).ServeHTTP(0x101c7dc40?, {0x1013d37d0, 0xc0000c21c0}, 0xc00047e400)
	github.com/rqlite/rqlite/http/service.go:460 +0x58f
net/http.serverHandler.ServeHTTP({0xc000524210?}, {0x1013d37d0?, 0xc0000c21c0?}, 0x6?)
	net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0000d6090, {0x1013d6ff8, 0xc0000d25a0})
	net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 32
	net/http/server.go:3086 +0x5cb
[rqlited] 2023/12/27 15:29:37 http: panic serving 127.0.0.1:51129: runtime error: invalid memory address or nil pointer dereference
goroutine 823 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1868 +0xb9
panic({0x100e0cb60?, 0x101c26e00?})
	runtime/panic.go:920 +0x270
github.com/rqlite/rqlite/db.normalizeRowValues({0xc0004a16c0, 0x1, 0x1?}, {0xc0004a1680, 0x1, 0x0?})
	github.com/rqlite/rqlite/db/db.go:1470 +0x27d
github.com/rqlite/rqlite/db.(*DB).queryStmtWithConn(0xc0001cc748?, 0xc0004f32c0, 0x0, {0x1013c98e0, 0xc000494940})
	github.com/rqlite/rqlite/db/db.go:920 +0x49a
github.com/rqlite/rqlite/db.(*DB).queryWithConn(0xc000116dd0?, 0x1013d6f18?, 0x40?, 0xc000494940)
	github.com/rqlite/rqlite/db/db.go:861 +0x27d
github.com/rqlite/rqlite/db.(*DB).Query(0xc000052a80, 0xc0004f3360, 0x8c?)
	github.com/rqlite/rqlite/db/db.go:809 +0x105
github.com/rqlite/rqlite/store.(*Store).Query(0xc000004300, 0xc000494900)
	github.com/rqlite/rqlite/store/store.go:1093 +0x665
github.com/rqlite/rqlite/http.(*Service).handleQuery(0xc000738240, {0x1013d37d0, 0xc0000c22a0}, 0xc00047e500, 0xc0001ccb68?)
	github.com/rqlite/rqlite/http/service.go:1216 +0x451
github.com/rqlite/rqlite/http.(*Service).ServeHTTP(0x101c7dc40?, {0x1013d37d0, 0xc0000c22a0}, 0xc00047e500)
	github.com/rqlite/rqlite/http/service.go:460 +0x58f
net/http.serverHandler.ServeHTTP({0xc00068e780?}, {0x1013d37d0?, 0xc0000c22a0?}, 0x6?)
	net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0004bb3b0, {0x1013d6ff8, 0xc0000d25a0})
	net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 32
	net/http/server.go:3086 +0x5cb

```

**Please include the Status, Nodes, and Expvar output from each node (or at least the Leader!)**

Can do if necessary - probably not for this.

**Comment by otoolep** [comment]
Thanks for the report. Can you reproduce using `curl` commands?

**Comment by bwarminski** [comment]
Yes same:

```
curl -G 'localhost:4001/db/query?pretty&timings' --data-urlencode "q=SELECT x'53514C697465' FROM test_types"
curl: (52) Empty reply from server
```

```
[rqlited] 2023/12/27 16:42:58 http: panic serving 127.0.0.1:52531: runtime error: invalid memory address or nil pointer dereference
goroutine 904 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1868 +0xb9
panic({0x100e0cb60?, 0x101c26e00?})
	runtime/panic.go:920 +0x270
github.com/rqlite/rqlite/db.normalizeRowValues({0xc000516e70, 0x1, 0x1?}, {0xc000516e40, 0x1, 0x0?})
	github.com/rqlite/rqlite/db/db.go:1470 +0x27d
github.com/rqlite/rqlite/db.(*DB).queryStmtWithConn(0xc0001c8748?, 0xc00029f7c0, 0x1, {0x1013c98e0, 0xc00052b4c0})
	github.com/rqlite/rqlite/db/db.go:920 +0x49a
github.com/rqlite/rqlite/db.(*DB).queryWithConn(0xc000116dd0?, 0x1013d6f18?, 0x40?, 0xc00052b4c0)
	github.com/rqlite/rqlite/db/db.go:861 +0x27d
github.com/rqlite/rqlite/db.(*DB).Query(0xc000052a80, 0xc00029f8b0, 0x8c?)
	github.com/rqlite/rqlite/db/db.go:809 +0x105
github.com/rqlite/rqlite/store.(*Store).Query(0xc000004300, 0xc00052b480)
	github.com/rqlite/rqlite/store/store.go:1093 +0x665
github.com/rqlite/rqlite/http.(*Service).handleQuery(0xc000738240, {0x1013d37d0, 0xc00048ad20}, 0xc00007c900, 0xc0001c8b68?)
	github.com/rqlite/rqlite/http/service.go:1216 +0x451
github.com/rqlite/rqlite/http.(*Service).ServeHTTP(0x101c7dc40?, {0x1013d37d0, 0xc00048ad20}, 0xc00007c900)
	github.com/rqlite/rqlite/http/service.go:460 +0x58f
net/http.serverHandler.ServeHTTP({0xc0004dd110?}, {0x1013d37d0?, 0xc00048ad20?}, 0x6?)
	net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0004bbd40, {0x1013d6ff8, 0xc0000d25a0})
	net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 32
	net/http/server.go:3086 +0x5cb

```

**Comment by otoolep** [comment]
Got it, thanks.

**Comment by otoolep** [comment]
Can repro, let me dig into it.

**Comment by otoolep** [comment]
I believe https://github.com/rqlite/rqlite/pull/1690 fixed this. Running the latest code:

```
~ $ rqlite
Welcome to the rqlite CLI.
Enter ".help" for usage hints.
Connected to http://127.0.0.1:4001 running version 8
127.0.0.1:4001> NTEGER, real_column REAL, text_column TEXT, blob_column BLOB, date_column TEXT, boolean_column INTEGER)
0 row affected
127.0.0.1:4001> .schema
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| sql                                                                                                                                                                  |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CREATE TABLE test_types (id INTEGER PRIMARY KEY, int_column INTEGER, real_column REAL, text_column TEXT, blob_column BLOB, date_column TEXT, boolean_column INTEGER) |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
127.0.0.1:4001> .schema
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| sql                                                                                                                                                                  |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CREATE TABLE test_types (id INTEGER PRIMARY KEY, int_column INTEGER, real_column REAL, text_column TEXT, blob_column BLOB, date_column TEXT, boolean_column INTEGER) |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
127.0.0.1:4001> select x'53514C697465' from test_types
+-----------------+
| x'53514C697465' |
+-----------------+
127.0.0.1:4001> 
```
No more panics.
