### ISSUE TITLE
Recovery process can result in old snapshot getting sent to node

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#1717]
Started with https://github.com/rqlite/rqlite/issues/1711

This may be another race between nodes coming up during the Recovery process and pushing various snapshots to each other, with no guarantees when they arrive and are installed -- and the reap removing older snapshots.

**Comment by otoolep** [comment]
@dwco-z - this may not be solvable through code, and may require some changes to the Recovery process steps.

**Comment by dwco-z** [comment]
@otoolep do you mean I should adjust the way I'm doing the recovery? Maybe adding some random timeout during each node's startup to reduce the chances of the race condition?

**Comment by otoolep** [comment]
@dwco-z -- maybe you can run the latest code, which will be available once this build completes: https://ci.appveyor.com/project/otoolep/rqlite/builds/49333481

I couldn't reproduce the issue locally, so your help would be good. Re-run your test, but with `-raft-log-level=INFO`, get the issue to occur, and then attach the logs to this bug.

**Comment by dwco-z** [comment]
Sure, will do

**Comment by dwco-z** [comment]
Here it is, I changed from-raft-log-level=DEBUG to -raft-log-level=INFO and captured the issue again:
[node2.log](https://github.com/rqlite/rqlite/files/14497271/node2.log)
[node3.log](https://github.com/rqlite/rqlite/files/14497272/node3.log)
[node1.log](https://github.com/rqlite/rqlite/files/14497270/node1.log)

**Comment by otoolep** [comment]
OK, as I suspect, more snapshot reaping going on.

It's not immediately clear to me how to solve this issue. I'll need to think about it.

**Comment by otoolep** [comment]
Couple of ideas, for my own reference:
- dig into why the Leader is sending an old snapshot to the follower
- consider reaping the snapshot in the future, if a node gets an older snapshot. Need to be cautious, as this could be a sign that something has gone wrong.

**Comment by dwco-z** [comment]
> OK, as I suspect, more snapshot reaping going on.
> 
> It's not immediately clear to me how to solve this issue. I'll need to think about it.

Ok, anytime you need me to test changes just let me know. I believe you could not reproduce the bug because of some timing difference as you mentioned before.

**Comment by dwco-z** [comment]
Just in case you need logs from the last created PR:
[node2.log](https://github.com/rqlite/rqlite/files/14509277/node2.log)
[node3.log](https://github.com/rqlite/rqlite/files/14509279/node3.log)
[node1.log](https://github.com/rqlite/rqlite/files/14509280/node1.log)

**Comment by otoolep** [comment]
Thanks, no surprises, what I expected is happening.

**Comment by otoolep** [comment]
@dwco-z -- can you run again, using the latest build from the same PR (I've updated the code a little) and run with `-raft-log-level=DEBUG`? Then send me the logs again -- thanks.

https://github.com/rqlite/rqlite/pull/1719

**Comment by otoolep** [comment]
@dwco-z -- can you run again, using the latest build from the same PR (I've updated the code a little) and run with `-raft-log-level=DEBUG`? Then send me the logs again -- thanks.

https://github.com/rqlite/rqlite/pull/1719

**Comment by dwco-z** [comment]
Sure

**Comment by otoolep** [comment]
I've actually merged the PR to master, because until we get to the bottom of this, getting an older snapshot breaks rqlite. The Raft paper does reference this possibility (and suggests ways to deal with it), but either the Raft layer itself is sending it incorrectly, or rqlite needs to handle it better. I want to know which it is before removing this check.

**Comment by dwco-z** [comment]
> I've actually merged the PR to master, because until we get to the bottom of this, getting an older snapshot breaks rqlite. The Raft paper does reference this possibility (and suggests ways to deal with it), but either the Raft layer itself is sending it incorrectly, or rqlite needs to handle it better. I want to know which it is before removing this check.

That makes sense. As soon as AppVeyor completes I'll send you the logs.

**Comment by dwco-z** [comment]
New logs 
[node2.log](https://github.com/rqlite/rqlite/files/14511103/node2.log)
[node3.log](https://github.com/rqlite/rqlite/files/14511104/node3.log)
[node1.log](https://github.com/rqlite/rqlite/files/14511106/node1.log)

**Comment by otoolep** [comment]
OK, thanks, logs are good to see. However, this issue is quite complex, with a lot of moving parts. Unless I can get it to happen locally, it's going to be difficult to solve. It's very timing-dependent and I don't know if it's a bug in the Raft code, a bug in rqlite code, or just that recovering a cluster like this it at the edge of what Raft and rqlite support (Recovery is not something that is described in the Raft paper).

I'll continue to see if I can reproduce this locally, but unless I do, I do not expect to solve this anytime soon. A more robust Recovery process may simply be to always recover *one* node first, and then join new nodes to it.

**Comment by otoolep** [comment]
@dwco-z -- when you run your script, does it exit automatically when the issue happens? Or are you just watching the logs?

**Comment by dwco-z** [comment]
> @dwco-z -- when you run your script, does it exit automatically when the issue happens? Or are you just watching the logs?

It exit automatically

> leader still not ready...
leader still not ready...
leader still not ready...
leader still not ready...
leader still not ready...
leader still not ready...
leader still not ready...
leader still not ready...
stopping rqlited...
stopped!
stopping rqlited...
stopped!
stopping rqlited...
stopped!
Traceback (most recent call last):
  File "C:\Projects\rqlite-throubleshoot\main.py", line 85, in <module>
    start_all_instances(all_instances)
  File "C:\Projects\rqlite-throubleshoot\main.py", line 55, in start_all_instances
    future.result()
  File "C:\Users\DayvidCastro\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DayvidCastro\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\DayvidCastro\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\rqlite-throubleshoot\main.py", line 49, in start_manager
    manager.start_rqlited(joinAddresses)
  File "C:\Projects\rqlite-throubleshoot\rqlite_manager.py", line 58, in start_rqlited
    raise Exception('something is wrong, leader is not ready...')
Exception: something is wrong, leader is not ready...
→ C:\Projects\rqlite-throubleshoot [rqlite-8.22.1-issue]›

**Comment by dwco-z** [comment]
I'll try running on my linux machine with python 3.8 to see if I can reproduce it there

**Comment by dwco-z** [comment]
I pushed some changes to rqlite-throubleshooting to make it compatible with linux,  and I was able to hit the issue in a linux mint using the latest release [rqlite-v8.22.2-linux-amd64.tar.gz](https://github.com/rqlite/rqlite/releases/download/v8.22.2/rqlite-v8.22.2-linux-amd64.tar.gz)

**Comment by otoolep** [comment]
Great, it's happening for me now with your latest script.

**Comment by otoolep** [comment]
Took about 1-2 minutes.

**Comment by dwco-z** [comment]
Nice!

**Comment by otoolep** [comment]
Sometimes the script is exiting, but the logs don't show the issue. Just an FYI.

**Comment by otoolep** [comment]
The logs are helping to understand this issue.

I'm not sure yet, but the RecoverNode documentation (which I got from Consul) does state that uncommitted entries and data loss can result from this process. When the issue happens I am seeing confusing elections taking place, and the logs are not entirely clear -- it could be the side-effects of this process. It may be that the RecoverNode process is not entirely bulletproof, and is a best-effort thing. Even the Raft docs say they've had issues in the past with this area of the code.

I will continue to think about this, and have some ideas for a fix, but I'm reluctant to make changes at this time that affect the core of rqlite for an edge case (which may even be a best effort thing). The only truly robust way to recover a cluster that has suffered a big loss is to take the SQLite database out from under a node (or use a backup) and rebuild the cluster.

**Comment by dwco-z** [comment]
One thing I find odd is that although snapshot and readyz?sync are two completely different concepts as you already mentioned, I cannot reproduce without the sync flag (I tried 260 times) while if I make other changes like inserting a random timeout before each node's start, I can still hit the issue eventually

**Comment by otoolep** [comment]
Sync simply changes the timing of the whole test substantially, that is my suspicion for the difference. Sync absolutely is a read-only operation, and does not change the operation of a node.

**Comment by dwco-z** [comment]
Oh, now I can see why the timing is relevant in leading to this series of events, yeah that makes sense

**Comment by otoolep** [comment]
Yeah, very timing dependent, that's why it takes a few attempts.

I can't rush into fixing this however. While in principle it's fairly easy to see a possible fix, the hard parts are dealing with crash scenarios. rqlite must handle crashing at anytime, particularly while taking a snapshot. There is important logic that rqlite runs at start-up, checking for inconsistencies. That logic today assumes that the most recent snapshot it finds is the desired one. That assumption could be changed by any fix for this particular issue -- and that might involve even more complicated consistency checking code, which can result in new bugs. Since crashing during snapshotting is much more likely to happen than this issue (`rqlited` can be killed at anytime by an operator), I have to consider changes very carefully.

**Comment by otoolep** [comment]
By crashing I also mean "exiting hard unexpectedly", perhaps due to `SIGKILL` being sent to `rqlited`.

**Comment by otoolep** [comment]
I've updated the node-recovery docs due to this issue.

**Comment by otoolep** [comment]
@dwco-z -- if my reasoning is correct here, I suspect you'll see much robust behavior if you increase the election timeout, maybe try 5 seconds. We want to reduce the rate of elections during the recovery process.

**Comment by otoolep** [comment]
@dwco-z -- correction, increase the election timeout for 2 out of the 3 nodes, thereby ensuring 1 node will be elected much faster than the other two nodes. Make two of the nodes, say, 10 seconds, and leave the other at 2 seconds. 

Yes, this is lots of special casing, but Node Recovery, by its nature, is meant to be something done under very controlled conditions.

**Comment by dwco-z** [comment]
I understand your point of view. I updated the rqlite-throubleshooting code with your recommendation of having one of the nodes to use a smaller raft-timeout (2s) while the others use a higher timeout (10s), but I couldn't notice any difference regarding making it more stable, it seems to be hitting the issue with roughly the same frequency. I'll try different settings to see if it improves.

**Comment by otoolep** [comment]
>having one of the nodes to use a smaller raft-timeout (2s) while the others use a higher timeout (10s), but I couldn't notice any difference regarding making it more stable,

That's interesting. I would definitely be interested in seeing the logs from such setup, where the problem happens. The logs should show clearly that the other 2 nodes take much longer to trigger an election.

**Comment by dwco-z** [comment]
Sure, I just hit a snapshot issue in the second attempt:

[node1.log](https://github.com/rqlite/rqlite/files/14542723/node1.log)

[node3.log](https://github.com/rqlite/rqlite/files/14542722/node3.log)

[node2.log](https://github.com/rqlite/rqlite/files/14542721/node2.log)

**Comment by otoolep** [comment]
Can you try bumping the timeout to 30s on two of the nodes? Run the test again, send me the logs if you hit it.

**Comment by dwco-z** [comment]
[node2.log](https://github.com/rqlite/rqlite/files/14543030/node2.log)
[node3.log](https://github.com/rqlite/rqlite/files/14543032/node3.log)
[node1.log](https://github.com/rqlite/rqlite/files/14543033/node1.log)

**Comment by otoolep** [comment]
OK, thanks, well clearly I don't fully understand the innards of some of the Raft code because that flag is not having the effect I want, at least not for the very first election. The appears to be going straight to candidate.

I'll just need to keep digging into the Raft code.

**Comment by otoolep** [comment]
The snapshotting system has been changed substantially so this issue is moot.
