### ISSUE TITLE
panic upon receiving a .table command

### ISSUE THREAD

**Issue by glycerine** [rqlite/rqlite#253]
rqlited at tip (21ae24d8d8e0003e658562079b74c55e35993d53), osx 10.11.6, go1.8rc1. with latest github.com/mattn/go-sqlite3 (eff6379ba09b2fca7aa8216f2132d4c170ed9d46), the rqlite .table command (probably any command really), causes rqlited to panic

~~~
$ rqlited tmp
rqlited tmp

            _ _ _           _
           | (_) |         | |
  _ __ __ _| |_| |_ ___  __| |
 | '__/ _  | | | __/ _ \/ _  |  The lightweight, distributed
 | | | (_| | | | ||  __/ (_| |  relational database.
 |_|  \__, |_|_|\__\___|\__,_|
         | |
         |_|

[rqlited] 2017/01/12 17:00:02 rqlited starting, version 3, commit unknown, branch unknown
[tcp] 2017/01/12 17:00:02 mux serving on 127.0.0.1:4002, advertising 127.0.0.1:4002
[store] 2017/01/12 17:00:02 SQLite in-memory database opened
[store] 2017/01/12 17:00:02 enabling single-node mode
[cluster] 2017/01/12 17:00:02 service listening on 127.0.0.1:4002
2017/01/12 17:00:02 [INFO] raft: Node at 127.0.0.1:4002 [Follower] entering Follower state (Leader: "")
[rqlited] 2017/01/12 17:00:03 failed to set peer for 127.0.0.1:4002 to localhost:4001: no leader available (retrying)
2017/01/12 17:00:04 [WARN] raft: Heartbeat timeout from "" reached, starting election
2017/01/12 17:00:04 [INFO] raft: Node at 127.0.0.1:4002 [Candidate] entering Candidate state
2017/01/12 17:00:04 [DEBUG] raft: Votes needed: 1
2017/01/12 17:00:04 [DEBUG] raft: Vote granted from 127.0.0.1:4002. Tally: 1
2017/01/12 17:00:04 [INFO] raft: Election won. Tally: 1
2017/01/12 17:00:04 [INFO] raft: Node at 127.0.0.1:4002 [Leader] entering Leader state
2017/01/12 17:00:04 [DEBUG] raft: Node 127.0.0.1:4002 updated peer set (2): [127.0.0.1:4002]
[rqlited] 2017/01/12 17:00:04 set peer for 127.0.0.1:4002 to localhost:4001
[http] 2017/01/12 17:00:04 service listening on localhost:4001
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x434de71]

goroutine 26 [running]:
github.com/rqlite/rqlite/db.(*DB).Execute.func1(0xc42004baf0, 0x45d4000, 0xc420194090, 0xc420151c40, 0x1, 0x4, 0x4513901, 0x0, 0x0)
	/Users/me/go/src/github.com/rqlite/rqlite/db/db.go:251 +0x281
github.com/rqlite/rqlite/db.(*DB).Execute(0xc420194090, 0xc420151c40, 0x1, 0x4, 0xc420140100, 0x0, 0x0, 0x4, 0xc42004bf78, 0x4)
	/Users/me/go/src/github.com/rqlite/rqlite/db/db.go:275 +0xca
github.com/rqlite/rqlite/store.(*Store).Apply(0xc4200b1080, 0xc42021e0c0, 0x480d640, 0xed00a1d01)
	/Users/me/go/src/github.com/rqlite/rqlite/store/store.go:632 +0x440
github.com/hashicorp/raft.(*Raft).runFSM(0xc4200f2800)
	/Users/me/go/src/github.com/hashicorp/raft/raft.go:595 +0xc79
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
	/Users/me/go/src/github.com/hashicorp/raft/raft.go:258 +0x2a
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc4200f2800, 0xc4201a4240)
	/Users/me/go/src/github.com/hashicorp/raft/state.go:142 +0x53
created by github.com/hashicorp/raft.(*raftState).goFunc
	/Users/me/go/src/github.com/hashicorp/raft/state.go:143 +0x66
$
~~~

**Comment by otoolep** [comment]
Thanks for your report. As per https://github.com/rqlite/rqlite/blob/master/README.md#limitations commands like that are supported. It shouldn't panic however. I'll fix that.

**Comment by glycerine** [comment]
r is nil at github.com/rqlite/rqlite/db/db.go:251, even for empty ";" command. I suspect some wierdness with the go-sqlite3 driver and/or go1.8rc1.

**Comment by otoolep** [comment]
Can you please show me the command that first triggered this? What sequence of queries did you pump in, from the very start?

**Comment by otoolep** [comment]
How did you pump `.table` in?

**Comment by glycerine** [comment]
rqlite command: ";" or any command. `rqlited` will crash on its own if there is an existing database; no command from `rqlite` required.

~~~
$ rqlite
127.0.0.1:4001> ;
ERR! Post http://127.0.0.1:4001/db/execute?pretty&timings: EOF
127.0.0.1:4001> 
~~~

**Comment by glycerine** [comment]
both `r` and `err` are nil at db/db.go:251 when the panic happens.

**Comment by otoolep** [comment]
OK, I can repo. It looks like something in the newer SQL code, 'cos older code is OK.

**Comment by glycerine** [comment]
agreed. there's new code in both go1.8rc1 database and new code that uses it in the go-sqlite3 driver.

**Comment by glycerine** [comment]
do you have a known-good git hash for github.com/mattn/go-sqlite3?

**Comment by glycerine** [comment]
also happens with `go1.7.3 darwin/amd64`, so it doesn't appear to be due to go1.8rc1.

**Comment by otoolep** [comment]
You could download a binary from the https://github.com/rqlite/rqlite/releases or wait until I merge https://github.com/rqlite/rqlite/pull/254

**Comment by glycerine** [comment]
The latest release has the panic as well.

**Comment by otoolep** [comment]
Weird -- that is strange, since I didn't get it to happen locally at first (perhaps I was mistaken). I can repo it now though.

**Comment by otoolep** [comment]
Thanks for the report. Top of tree should handle this now.

**Comment by otoolep** [comment]
I still need to look into something similar for the query path, but it's more of an internal issue right now.

**Comment by otoolep** [comment]
This is fixed now.
