### ISSUE TITLE
Connection closed called twice can result in panic

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#497]
On the new self_closing_conn branch, if connection close is called twice, it can result in a panic. This can happen if the connection is explicitly closed concurrently with a close due to an idle-timeout close.

More work with the mutexes is needed here.

**Comment by otoolep** [comment]
```
[rqlited] 2018/05/30 10:19:11 rqlited starting, version 5, commit unknown, branch unknown
[rqlited] 2018/05/30 10:19:11 go1.10.2, target architecture is amd64, operating system target is linux
[store] 2018/05/30 10:19:11 opening store with node ID localhost:4002
[store] 2018/05/30 10:19:11 ensuring directory at /usr/local/google/home/otoolep/coding/rqlite/src/github.com/rqlite/rqlite/cmd/rqlited/data exists
[store] 2018/05/30 10:19:11 SQLite in-memory database opened
[raft] 2018/05/30 10:19:11 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:localhost:4002 Address:127.0.0.1:4002}]
[store] 2018/05/30 10:19:11 no bootstrap needed
[rqlited] 2018/05/30 10:19:11 no join addresses set
[raft] 2018/05/30 10:19:11 [INFO] raft: Node at 127.0.0.1:4002 [Follower] entering Follower state (Leader: "")
[raft] 2018/05/30 10:19:13 [WARN] raft: Heartbeat timeout from "" reached, starting election
[raft] 2018/05/30 10:19:13 [INFO] raft: Node at 127.0.0.1:4002 [Candidate] entering Candidate state in term 7
[raft] 2018/05/30 10:19:13 [DEBUG] raft: Votes needed: 1
[raft] 2018/05/30 10:19:13 [DEBUG] raft: Vote granted from localhost:4002 in term 7. Tally: 1
[raft] 2018/05/30 10:19:13 [INFO] raft: Election won. Tally: 1
[raft] 2018/05/30 10:19:13 [INFO] raft: Node at 127.0.0.1:4002 [Leader] entering Leader state
connection made: 16596347714875767075
applying disconnect: 16596347714875767075
connection made: 7571497329709358551
connection made: 9654183847763689129
applying disconnect: 16596347714875767075
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7b27e8]

goroutine 26 [running]:
github.com/rqlite/rqlite/store.(*Store).Apply(0xc4200d6fc0, 0xc42017d1d0, 0x0, 0x0)
	/usr/local/google/home/otoolep/coding/rqlite/src/github.com/rqlite/rqlite/store/store.go:1095 +0xa08
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc4201c01b0)
	/usr/local/google/home/otoolep/coding/rqlite/src/github.com/hashicorp/raft/fsm.go:57 +0x15a
github.com/hashicorp/raft.(*Raft).runFSM(0xc420101080)
	/usr/local/google/home/otoolep/coding/rqlite/src/github.com/hashicorp/raft/fsm.go:120 +0x2fa
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
	/usr/local/google/home/otoolep/coding/rqlite/src/github.com/hashicorp/raft/api.go:506 +0x2a
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc420101080, 0xc4200a55b0)
	/usr/local/google/home/otoolep/coding/rqlite/src/github.com/hashicorp/raft/state.go:146 +0x53
created by github.com/hashicorp/raft.(*raftState).goFunc
	/usr/local/google/home/otoolep/coding/rqlite/src/github.com/hashicorp/raft/state.go:144 +
```
