### ISSUE TITLE
Client blocked and timeout when rqlited creates new snapshot and compacts logs

### ISSUE THREAD

**Issue by little-pan** [rqlite/rqlite#543]
## The problem description
1. The client logs
```
13:50:09.672 i = 37000000
13:50:13.082 i = 37100000
13:50:16.160 i = 37200000
13:50:19.756 i = 37300000
13:50:23.703 i = 37400000
13:50:27.072 i = 37500000
13:50:30.629 i = 37600000
13:50:34.414 i = 37700000
13:50:37.629 i = 37800000
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:143)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1011)
        at com.rqlite.impl.ExecuteRequest.execute(ExecuteRequest.java:19)
        at com.rqlite.impl.RqliteImpl.Execute(RqliteImpl.java:63)
        at Test.main(Test.java:60)
13:50:59.346[Error] exit, i = 37848000
13:50:59.348 rows: 10403000, time: 503074ms
```
2. The rqlited logs
```
# node.0 192.168.145.101:3001
2019/01/11 13:51:15 [INFO] raft: Starting snapshot up to 57854
2019/01/11 13:51:15 [INFO] snapshot: Creating new snapshot at /root/rqlite/rqlite-v4.4.0-linux-amd64/node.0/snapshots/1-57854-1547185875275.tmp
2019/01/11 13:51:39 [INFO] snapshot: reaping snapshot /root/rqlite/rqlite-v4.4.0-linux-amd64/node.0/snapshots/1-37823-1547183303901
2019/01/11 13:51:39 [INFO] raft: Compacting logs from 37213 to 47615
2019/01/11 13:52:00 [INFO] raft: Snapshot to 57854 complete
```

## rqlited configuration
A standalone rqlited server(v4.4.0) runs on centos 7 x86_64:
```
./rqlited -http-addr 192.168.145.101:3001 -raft-addr localhost:3002 ./node.0 1>./rq.3001.stdout 2>./rq.3001.stderr &
```

## The test case
```java
import com.rqlite.*;
import com.rqlite.dto.*;

import java.util.*;
import java.text.*;

// standalone 2~3w rows/s
public class Test {

	public static void main(String args[]){
		String sql = null, host = "localhost";
		int port   = 4001;
		int rowNum = 10000000, batch = 1000, start = 0;

		// parse args
		for(int i = 0, size = args.length; i < size; ++i){
			final String arg = args[i];
			if("-?".equals(arg) || "--help".equals(arg)){
				usage();
				System.exit(0);
			}else if("--sql".equals(arg)){
				sql = args[++i];
			}else if("--host".equals(arg)){
				host = args[++i];
			}else if("--port".equals(arg)){
				port = Integer.parseInt(args[++i]);
			}else if("--rows".equals(arg)){
				rowNum = Integer.parseInt(args[++i]);
			}else if("--batch".equals(arg)){
				batch = Integer.parseInt(args[++i]);
			}else if("--start".equals(arg)){
				start = Integer.parseInt(args[++i]);
			}else{
				usage();
				System.exit(1);
			}
		}

		final long ts = System.currentTimeMillis();
		// Declare variables.
		ExecuteResults results = null;
		QueryResults rows = null;

		// Get a connection to a rqlite node.
		Rqlite rqlite = RqliteFactory.connect("http", host, port);

		// Insert records
		if(sql == null || sql.trim().length() == 0){
			final List<String> sqls = new ArrayList<>(batch);
			final DateFormat df = new SimpleDateFormat("HH:mm:ss.SSS");
			int i = start;
			for(int j = i + rowNum; i < j; ){
				final int n = Math.min(batch, j - start);
				for(int k = 0; k < n; ++k, ++i){
					sql = String.format("delete from accounts where id = %d", i);
					sqls.add(sql);
					sql = String.format("insert into accounts(id, name, balance)values(%d, '%s', %d)", i, "账户-"+i, i%1000000);
					sqls.add(sql);
				}
				results = rqlite.Execute(sqls.toArray(new String[sqls.size()]), true);
				sqls.clear();
				if(results == null){
					System.err.println(String.format("%s[Error] exit, i = %d ", df.format(new Date()), i - n));
					break;
				}
				if((i%100000) == 0){
					System.out.println(String.format("%s i = %d", df.format(new Date()), i));
				}
			}
			System.out.println(String.format("%s rows: %d, time: %dms", 
				df.format(new Date()), i - start, (System.currentTimeMillis()-ts)));
		}else{
			// Query some records in the table.
			rows = rqlite.Query(sql, Rqlite.ReadConsistencyLevel.STRONG);
			System.out.println(rows.toString());
		}
	}

	static void usage(){
		System.out.println("Usage: java Test [--host <ip>] [--port <n>] {[--rows <n>] [--batch <n>] [--start <n>]|[--sql <sql>]}");
	}

}
```

**Comment by otoolep** [comment]
This is the way Raft works. It must take a consistent snapshot of the log, so accesses to it are blocked during the snapshotting process.

You can play with the number of logs per snap, via a command line option. You can have more, shorter snapshots, or fewer, longer snapshots.
