### ISSUE TITLE
rqlite client fails with panic when called with parameters

### ISSUE THREAD

**Issue by xakepp35** [rqlite/rqlite#819]
**What version are you running?**

```
runtime:
    version: go1.16.2
sqlite3:
    version: 3.35.4
build:
  branch: unknown
  build_time: unknown
  commit: unknown
  version: 6
```

**What did you do?**
call the client inside container with parameters:
`$ oc rsh rqlite-0 ./rqlite -H rqlite-0.rqlite`

**What did you expect to happen?**
To be able to type sql commands

**What happened instead?**
```
Defaulting container name to rqlite.
Use 'oc describe pod/rqlite-0 -n ####' to see all of the containers in this pod.
Welcome to the rqlite CLI. Enter ".help" for usage hints.
Connected to version 6
rqlite-0.rqlite:4001> panic: runtime error: slice bounds out of range [23:0]

goroutine 1 [running]:
github.com/Bowery/prompt.(*Buffer).Refresh(0xc00025fae0, 0x1000, 0x1000)
	/home/theog/go/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/buffer_unix.go:54 +0x4fe
github.com/Bowery/prompt.(*Terminal).setup(0xc0000260c0, 0xc00025fae0, 0x7c0420, 0xc000010028, 0x16, 0x16, 0xc00025fa48)
	/home/theog/go/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/term.go:226 +0xac
github.com/Bowery/prompt.(*Terminal).prompt(0xc0000260c0, 0xc00025fae0, 0x7c0420, 0xc000010028, 0x1, 0xc00001e078, 0x16, 0x4680c5)
	/home/theog/go/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/term.go:337 +0x6a
github.com/Bowery/prompt.(*Terminal).GetPrompt(0xc0000260c0, 0xc00001e060, 0x15, 0x6c44fa, 0x0, 0xc000023501, 0xc00025fb94)
	/home/theog/go/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/term.go:165 +0x125
github.com/Bowery/prompt.(*Terminal).Custom(0xc0000260c0, 0xc00001e060, 0x15, 0xc00025fbe8, 0xc00025fbf8, 0x6c240d, 0xc0000c2000, 0xc000020540)
	/home/theog/go/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/term.go:130 +0x45
github.com/Bowery/prompt.(*Terminal).Basic(0xc0000260c0, 0xc00001e060, 0x15, 0x0, 0x2, 0xc00001e060, 0x15, 0x17)
	/home/theog/go/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/term.go:78 +0x70
main.main.func1(0xc0000f4370, 0x0, 0x0)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/cmd/rqlite/main.go:83 +0x6a5
github.com/mkideal/cli.(*Command).RunWith(0xc0000de360, 0xc00009a160, 0x2, 0x2, 0x7c0880, 0xc0000c2008, 0x0, 0x0, 0x0, 0x0, ...)
	/home/theog/go/pkg/mod/github.com/mkideal/cli@v0.2.5/command.go:219 +0x289
github.com/mkideal/cli.(*Command).Run(...)
	/home/theog/go/pkg/mod/github.com/mkideal/cli@v0.2.5/command.go:176
github.com/mkideal/cli.RunWithArgs(0x700f80, 0xc000128310, 0xc00009a150, 0x3, 0x3, 0x775fe0, 0x0, 0x0, 0x0, 0xc00008e058)
	/home/theog/go/pkg/mod/github.com/mkideal/cli@v0.2.5/cli.go:30 +0x1ad
github.com/mkideal/cli.Run(...)
	/home/theog/go/pkg/mod/github.com/mkideal/cli@v0.2.5/cli.go:15
main.main()
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/cmd/rqlite/main.go:49 +0x8c
command terminated with exit code 2
```

**Comment by xakepp35** [comment]
Probably this is linked issue: https://github.com/Bowery/prompt/issues/15
The problem in library you decided to use leads to a problem in client. If library is not supported well - maybe use more reliable and stable library?

**Comment by otoolep** [comment]
I don't understand this issue. How does this command `oc rsh rqlite-0 ./rqlite -H rqlite-0.rqlite` result in problematic parameters being passed to `rqlite`? I can't repro this issue. Can you explain?

**Comment by otoolep** [comment]
No reponse, closing.

**Comment by robinp** [comment]
Hi @otoolep! Ran into this why toying around in docker, let me try to describe a potential repro:

```
$ docker images | grep rqlite
rqlite/rqlite                                       latest              a7d4f96242bf   5 weeks ago     34.9MB
```
Start up single leader:

```
$ docker run --rm --name node1 -p4001:4001 --expose 4002 --network rqnet --entrypoint /bin/rqlited rqlite/rqlite -node-id node1 -http-addr 0.0.0.0:4001 -http-adv-addr node1:4001 -raft-addr 0.0.0.0:4002 -raft-adv-addr node1:4002  /rqlite/file/data
```

In other terminal:
```
$ docker run --rm -it --network rqnet --entrypoint /bin/rqlite rqlite/rqlite  -H node1
```
Note! It is pretty undeterministic, out of 10 runs sometime I get all fails, sometime 3-4 fails. Probably some other random hidden factors, but worth a try.

Also, I built the go binary locally, when running that directly (not via Docker), the problem never happens.

I suspect this might be something about the Bowery/prompt's buffer handling logic observing a too-small column terminal (likely zero or something) which leads to crash with the juggling logic in https://github.com/Bowery/prompt/blob/fa8279994f75f982bdae3c827a3afffd78a6fe0d/buffer_unix.go#L34. Maybe some race condition about initing terminal on docker startup? Not much experience with that.

Searching leads to https://github.com/docker/for-linux/issues/314, the `stty -a` command reveals the current line/col settings of the tty. Indeed, doing `/bin/sh` entrypoint to the image, and then calling `stty -a` prints some specific size (and actually starting `rqlite -H node1` from the shell then  works), but using `/bin/stty` as entrypoint doesn't (yet) show any sizes.

So sounds like some race condition between prompt printing and the tty getting a size. Work-around is relatively easy (start sh entrypoint, run rqlite from there; or well, run rqlite directly), so not really bugging me.

**Comment by otoolep** [comment]
OK, thanks -- can you show me the panic trace you get?

**Comment by otoolep** [comment]
Is is the same as the report?

**Comment by robinp** [comment]
Hello - yes, it seems quite similar, but pasting here. Note I'm just running this with `docker run -t` (missing `-i`), since this way the trace is more legible (no alignment errors), but otherwise same.

```
$ docker run --rm -t --network rqnet --entrypoint /bin/rqlite rqlite/rqlite  -H node1
Welcome to the rqlite CLI. Enter ".help" for usage hints.
Version v7.13.1, commit 62e43d8de1784178b876ec33867b80aac0554282, branch master
Connected to rqlited version v7.13.1
node1:4001> panic: runtime error: slice bounds out of range [13:0]

goroutine 1 [running]:
github.com/Bowery/prompt.(*Buffer).Refresh(0xc00025fa40)
	/tmp/tmp.mp932HYpDC/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/buffer_unix.go:54 +0x346
github.com/Bowery/prompt.(*Terminal).setup(0x1?, 0xc00025fa40, {0x798620?, 0xc0000be088})
	/tmp/tmp.mp932HYpDC/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/term.go:226 +0x188
github.com/Bowery/prompt.(*Terminal).prompt(0xc000092480, 0xc00025fa40, {0x798620?, 0xc0000be088?})
	/tmp/tmp.mp932HYpDC/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/term.go:337 +0x4b
github.com/Bowery/prompt.(*Terminal).GetPrompt(0xc000092480, {0xc0000cc5d0?, 0xc00025fad8?})
	/tmp/tmp.mp932HYpDC/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/term.go:165 +0xe5
github.com/Bowery/prompt.(*Terminal).Custom(0xc000028005?, {0xc0000cc5d0, 0xb}, 0xc00025fb10)
	/tmp/tmp.mp932HYpDC/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/term.go:130 +0x45
github.com/Bowery/prompt.(*Terminal).Basic(0xc000092480?, {0xc0000cc5d0?, 0x2?}, 0x2?)
	/tmp/tmp.mp932HYpDC/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/term.go:78 +0x45
main.main.func1(0xc0000e2370)
	/tmp/tmp.mp932HYpDC/src/github.com/rqlite/rqlite/cmd/rqlite/main.go:120 +0x8a5
github.com/mkideal/cli.(*Command).RunWith(0xc0000d2360, {0xc0000a2160, 0x2, 0x2}, {0x0?, 0x0?}, {0x0, 0x0}, {0x0, 0x0, ...})
	/tmp/tmp.mp932HYpDC/pkg/mod/github.com/mkideal/cli@v0.2.7/command.go:219 +0x399
github.com/mkideal/cli.(*Command).Run(...)
	/tmp/tmp.mp932HYpDC/pkg/mod/github.com/mkideal/cli@v0.2.7/command.go:176
github.com/mkideal/cli.RunWithArgs({0x6c6e80?, 0xc000152000?}, {0xc0000a2150?, 0x3?, 0x3?}, 0x745cc0?, {0x0?, 0x6bb160?, 0xc0000021a0?})
	/tmp/tmp.mp932HYpDC/pkg/mod/github.com/mkideal/cli@v0.2.7/cli.go:30 +0x230
github.com/mkideal/cli.Run(...)
	/tmp/tmp.mp932HYpDC/pkg/mod/github.com/mkideal/cli@v0.2.7/cli.go:15
main.main()
	/tmp/tmp.mp932HYpDC/src/github.com/rqlite/rqlite/cmd/rqlite/main.go:62 +0x5e
```
